[profile.default]
src = 'src'
out = 'out'
libs = ['lib']
fs_permissions = [{ access = "read-write", path = "./" }]
bytecode_hash = "none"                                    # to get deterministic deployed code

solc_version = "0.8.17"
optimizer = true
optimizer_runs = 200

[rpc_endpoints]
mainnet = "https://mainnet.infura.io/v3/${INFURA_API_KEY}"
goerli = "https://goerli.infura.io/v3/${INFURA_API_KEY}"
sepolia = "https://sepolia.infura.io/v3/${INFURA_API_KEY}"
polygon = "https://polygon-mainnet.infura.io/v3/${INFURA_API_KEY}"
mumbai = "https://polygon-mumbai.infura.io/v3/${INFURA_API_KEY}"
fevm = "https://api.calibration.node.glif.io/rpc/v1"
anvil = "http://127.0.0.1:8545"

[etherscan]
goerli = { key = "${ETHERSCAN_API_KEY}" }
sepolia = { key = "${ETHERSCAN_API_KEY}" }
mumbai = { key = "${POLYGONSCAN_API_KEY}" }
mainnet = { key = "${ETHERSCAN_API_KEY}" }
polygon = { key = "${POLYGONSCAN_API_KEY}" }

# See more config options https://github.com/foundry-rs/foundry/tree/master/config
